version: '3.7'
name: inception
volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind 

networks:
  inception-network:
    driver: bridge
    name: inception-network

services:
  mariadb:
    image: mariadb:inception
    env_file: 
      - .env
    build:
      context: ./requirements/mariadb/
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception-network

  wordpress:
    image: wordpress:inception
    env_file: .env
    build:
      context: ./requirements/wordpress
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=${DB_HOST}
    depends_on:
      - mariadb
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception-network

  nginx:
    image: nginx:inception
    build:
      context: ./requirements/nginx/
    env_file: 
      - .env
    container_name: nginx
    depends_on:
      - wordpress
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/wordpress
      - ./requirements/nginx/conf:/etc/nginx/conf.d
    networks:
      - inception-network
