version: '3.8'

name: inception

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: ~/data/mariadb
      o: bind 
  portainer:
    name: portainer

networks:
  inception-network:
    driver: bridge
    name: inception-network

services:
  mariadb:
    image: mariadb:inception
    init: true
    build:
      context: ./requirements/mariadb/
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_ROOT_PASS=${DB_ROOT_PASS}
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception-network

  wordpress:
    image: wordpress:inception
    init: true
    env_file: .env
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception-network

  nginx:
    image: nginx:inception
    init: true
    build:
      context: ./requirements/nginx/
      args:
        - SSL_PASSPHRASE=${SSL_PASSPHRASE}
        - SSL_CERTIFICATE=${SSL_CERTIFICATE}
        - SSL_CERTIFICATE_KEY=${SSL_CERTIFICATE_KEY}
        - SSL_PASSWORD_FILE=${SSL_PASSWORD_FILE}
    env_file: 
        - SSL_CERTIFICATE=${SSL_CERTIFICATE}
        - SSL_CERTIFICATE_KEY=${SSL_CERTIFICATE_KEY}
        - SSL_PASSWORD_FILE=${SSL_PASSWORD_FILE}
    container_name: nginx
    depends_on:
      - wordpress
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks: 
      - inception-network

  redis:
    image: redis:inception
    init: true
    build:
      context: ./requirements/bonus/redis/
    container_name: redis
    depends_on:
      - wordpress
    restart: unless-stopped
    networks:
      - inception-network

  ftp:
    image: ftp:inception
    init: true
    build:
      context: ./requirements/bonus/ftp/
      args:
        - FTP_USER=${FTP_USER}
        - FTP_PASS=${FTP_PASS}
        - FTP_HOME=${FTP_HOME}
    container_name: ftp
    depends_on:
      - wordpress
    restart: unless-stopped
    ports:
      - "20-21:20-21"
      - "40000-40009:40000-40009"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception-network
  
  adminer:
    image: adminer:inception
    init: true
    build:
      context: ./requirements/bonus/adminer
    container_name: adminer
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - inception-network

  portfolio:
    image: portfolio:inception
    init: true
    build:
      context: ./requirements/bonus/portfolio/
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - inception-network

  portainer:
    image: portainer:inception
    init: true
    build:
      context: ./requirements/bonus/portainer/
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443"
    networks:
      - inception-network
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
